global:
  sysdig:
    accessKey: 9ab3-c3d2-f42e-f42e-5c04                 # Sysdig Agent Access Key FAKE
    region: ${sysdigRegion}
  kspm:
    deploy: true
  clusterConfig:
    name: ${sysdigClusterName}
agent:
  sysdig:
    settings:
      collector_port: 6443
nodeAnalyzer:
  nodeAnalyzer:
    benchmarkRunner:
      deploy: false
    runtimeScanner:
      settings:
        eveEnabled: true
  secure:
    vulnerabilityManagement:
      newEngineOnly: true
